[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
decentralized_webrtc = "9VZTmG79FSDSfuJFi5SgVd4FdyJBX5gB6SDvN6QF95Ki"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
